// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/billing" | "/blog" | "/blog/[slug]" | "/campaigns" | "/conversations" | "/dashboard" | "/dashboard/inbox" | "/dashboard/jobs" | "/dashboard/jobs/[id]" | "/dashboard/leads" | "/dashboard/leads/[id]" | "/dashboard/outbound" | "/dashboard/pipeline" | "/dashboard/scanner" | "/dashboard/scanner/harness" | "/dashboard/schedule" | "/dashboard/settings" | "/login" | "/pipeline" | "/pipeline/[leadId]" | "/privacy" | "/settings" | "/terms"
type AppRouteHandlerRoutes = "/api/billing/checkout" | "/api/billing/portal" | "/api/campaigns/send" | "/api/conversations/send" | "/api/dev/quick-login" | "/api/inngest" | "/api/jobs" | "/api/jobs/[id]" | "/api/leads" | "/api/leads/[id]" | "/api/leads/[id]/convert" | "/api/leads/[id]/signals" | "/api/opportunities" | "/api/opportunities/[id]/outbound-list" | "/api/outbound-lists" | "/api/outbound-lists/[id]/export" | "/api/outbound-lists/[id]/sync" | "/api/outbound/contacts" | "/api/outbound/import" | "/api/prospects" | "/api/referral-partners" | "/api/routing-rules" | "/api/routing-rules/[id]" | "/api/scanner" | "/api/scanner/events" | "/api/scanner/events/[id]/dispatch" | "/api/scanner/run" | "/api/settings/weather" | "/api/smartlead/webhook" | "/api/stripe/webhook" | "/api/twilio/sms/inbound" | "/api/twilio/status" | "/api/twilio/voice/inbound" | "/api/weather"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/billing/checkout": {}
  "/api/billing/portal": {}
  "/api/campaigns/send": {}
  "/api/conversations/send": {}
  "/api/dev/quick-login": {}
  "/api/inngest": {}
  "/api/jobs": {}
  "/api/jobs/[id]": { "id": string; }
  "/api/leads": {}
  "/api/leads/[id]": { "id": string; }
  "/api/leads/[id]/convert": { "id": string; }
  "/api/leads/[id]/signals": { "id": string; }
  "/api/opportunities": {}
  "/api/opportunities/[id]/outbound-list": { "id": string; }
  "/api/outbound-lists": {}
  "/api/outbound-lists/[id]/export": { "id": string; }
  "/api/outbound-lists/[id]/sync": { "id": string; }
  "/api/outbound/contacts": {}
  "/api/outbound/import": {}
  "/api/prospects": {}
  "/api/referral-partners": {}
  "/api/routing-rules": {}
  "/api/routing-rules/[id]": { "id": string; }
  "/api/scanner": {}
  "/api/scanner/events": {}
  "/api/scanner/events/[id]/dispatch": { "id": string; }
  "/api/scanner/run": {}
  "/api/settings/weather": {}
  "/api/smartlead/webhook": {}
  "/api/stripe/webhook": {}
  "/api/twilio/sms/inbound": {}
  "/api/twilio/status": {}
  "/api/twilio/voice/inbound": {}
  "/api/weather": {}
  "/billing": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/campaigns": {}
  "/conversations": {}
  "/dashboard": {}
  "/dashboard/inbox": {}
  "/dashboard/jobs": {}
  "/dashboard/jobs/[id]": { "id": string; }
  "/dashboard/leads": {}
  "/dashboard/leads/[id]": { "id": string; }
  "/dashboard/outbound": {}
  "/dashboard/pipeline": {}
  "/dashboard/scanner": {}
  "/dashboard/scanner/harness": {}
  "/dashboard/schedule": {}
  "/dashboard/settings": {}
  "/login": {}
  "/pipeline": {}
  "/pipeline/[leadId]": { "leadId": string; }
  "/privacy": {}
  "/settings": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
