// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/campaigns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/campaigns">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/campaigns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/conversations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/conversations">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/conversations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/inbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/inbox">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/inbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/jobs/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/jobs/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/jobs/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/jobs">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/leads/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/leads/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/leads/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/leads">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/outbound/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/outbound">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/outbound/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/pipeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/pipeline">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/pipeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/scanner/harness/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/scanner/harness">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/scanner/harness/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/scanner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/scanner">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/scanner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/schedule">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/pipeline/[leadId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline/[leadId]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/pipeline/[leadId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/pipeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/pipeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/portal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/portal">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/portal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/campaigns/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/campaigns/send">> = Specific
  const handler = {} as typeof import("../../src/app/api/campaigns/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/conversations/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conversations/send">> = Specific
  const handler = {} as typeof import("../../src/app/api/conversations/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dev/quick-login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/quick-login">> = Specific
  const handler = {} as typeof import("../../src/app/api/dev/quick-login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inngest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inngest">> = Specific
  const handler = {} as typeof import("../../src/app/api/inngest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leads/[id]/convert/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/[id]/convert">> = Specific
  const handler = {} as typeof import("../../src/app/api/leads/[id]/convert/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leads/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/leads/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leads/[id]/signals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/[id]/signals">> = Specific
  const handler = {} as typeof import("../../src/app/api/leads/[id]/signals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads">> = Specific
  const handler = {} as typeof import("../../src/app/api/leads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/opportunities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/opportunities">> = Specific
  const handler = {} as typeof import("../../src/app/api/opportunities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/outbound/contacts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/outbound/contacts">> = Specific
  const handler = {} as typeof import("../../src/app/api/outbound/contacts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/outbound/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/outbound/import">> = Specific
  const handler = {} as typeof import("../../src/app/api/outbound/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/routing-rules/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/routing-rules/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/routing-rules/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/routing-rules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/routing-rules">> = Specific
  const handler = {} as typeof import("../../src/app/api/routing-rules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/scanner/events/[id]/dispatch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scanner/events/[id]/dispatch">> = Specific
  const handler = {} as typeof import("../../src/app/api/scanner/events/[id]/dispatch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/scanner/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scanner/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/scanner/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/scanner/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scanner">> = Specific
  const handler = {} as typeof import("../../src/app/api/scanner/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/scanner/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scanner/run">> = Specific
  const handler = {} as typeof import("../../src/app/api/scanner/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/settings/weather/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/weather">> = Specific
  const handler = {} as typeof import("../../src/app/api/settings/weather/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stripe/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/stripe/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/twilio/sms/inbound/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/twilio/sms/inbound">> = Specific
  const handler = {} as typeof import("../../src/app/api/twilio/sms/inbound/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/twilio/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/twilio/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/twilio/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/twilio/voice/inbound/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/twilio/voice/inbound">> = Specific
  const handler = {} as typeof import("../../src/app/api/twilio/voice/inbound/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/weather/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/weather">> = Specific
  const handler = {} as typeof import("../../src/app/api/weather/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
